### ISSUE TITLE
Failed to build examples on Mac OS Catalina

### ISSUE THREAD

**Issue by ACAVJW4H** [polymonster/pmtech#39]
Hey! I get the following error when I try to build the examples on Mac OS 10.15.2

```
(base) ➜  osx git:(master) make config=release
==== Building pen (release) ====
Creating ../../lib/osx/release
Creating obj/Release
input.cpp
job_threads.cpp
timer.cpp
memory.cpp
renderer_opengl.cpp
os.mm
In file included from ../../source/osx/os.mm:10:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Cocoa.framework/Headers/Cocoa.h:12:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:89:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSURLError.h:15:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreServices.framework/Headers/CoreServices.h:23:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/AE.framework/Headers/AE.h:20:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/CarbonCore.h:208:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/HFSVolumes.h:25:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/hfs/hfs_format.h:794:2: error: unknown type name 'uuid_string_t'; did you mean 'io_string_t'?
        uuid_string_t   ext_jnl_uuid;

```

**Comment by polymonster** [comment]
Hi, I am running the same macOS version on 2 different machines with no problems, so it is not an issue with the os.

Do you have the latest version of Xcode command line tools? Did you install them via brew? It seems like something could be wrong with your system setup and installations of thing from brew can sometimes cause conflicts with system headers.

I saw other mentions of the same error in a google search https://www.gitmemory.com/issue/rjeczalik/notify/180/503717448

**Comment by polymonster** [comment]
Here is the latest macOS build on travis succeeding if you want to use that for reference to help debug the issue https://travis-ci.org/polymonster/pmtech/jobs/643131269

**Comment by ACAVJW4H** [comment]
This is a clean new setup with Catalina. Tried removing and re-installing Xcode from the App Store  (The Latest version is 11.3.1 now) The above travis build is using version 9.4.1 and has clang-902 again latest is 1100. Might the error arise due to that?

**Comment by polymonster** [comment]
I’m not sure, it is late here I will need to take a look in more detail tomorrow.

It looks like you are building from the command line with make? Can you post the entire console log from whatever command you are running starting with whatever pmbuild command line you used.

**Comment by polymonster** [comment]
You should try building from Xcode itself instead of the commandline.

This kind of error just seems like badly configured environment, it’s a macOS sdk header missing a definition.

**Comment by ACAVJW4H** [comment]
My bad, you're right it's a configuration error due to brew installed libuuid. Forcing to use macOS' version resolves it. Basically;
`sudo mv /usr/local/include/uuid/uuid.h /usr/local/include/uuid/uuid.h.bak`
Terribly sorry to bother you.

**Comment by polymonster** [comment]
> My bad, you're right it's a configuration error due to brew installed libuuid. Forcing to use macOS' version resolves it. Basically;
> `sudo mv /usr/local/include/uuid/uuid.h /usr/local/include/uuid/uuid.h.bak`
> Terribly sorry to bother you.

No problem, glad you fixed the issue :) ✌🏻
