### ISSUE TITLE
error C3861: “renderer_tcp_resolve_ratio”

### ISSUE THREAD

**Issue by happydpc** [polymonster/pmtech#41]
Vulkan version cannot compile successfully. This is the error.

pmtech\source\pen\source\vulkan\renderer_vulkan.cpp(2183): error C3861: “renderer_tcp_resolve_ratio”

**Comment by polymonster** [comment]
Hi, I just submitted a potential fix for this, I am working on Mac right now so don't have Vulkan SDK I need to wait to get home to test, and I won't be around until Saturday.

Please bear in mind that the Vulkan implementation is still in progress quite a few of the samples work but there are missing features.. I have been working on some other stuff recently and mean to get back to Vulkan sometime soon!

you can check the progress of the project here: https://trello.com/b/ciujzpUT/pmtech

**Comment by polymonster** [comment]
This issue is now confirmed fixed
