### ISSUE TITLE
pthread_cancel

### ISSUE THREAD

**Issue by heitaoflower** [polymonster/pmtech#42]
No support pthread_cancel at android platform.

**Comment by polymonster** [comment]
I haven't been working on Android much I started and then refactored the rest of the platforms so android has fallen behind.. are you trying to get it working?

instead of pthread_cancel we could use pthread_exit on android

**Comment by heitaoflower** [comment]
so, I wondering if you could tell me why not go for  c++11 thread library as the primary option ?

**Comment by polymonster** [comment]
I started working on this before c++11 even existed.

The c++11 thread library does not allow you to specify stack size or thread affinity among other features.. which are things I do want to use on other console platforms I am using this on for work but not in the public repository.

**Comment by heitaoflower** [comment]
pthread_exit can only exit it self.
pthread_cancel can *exit* others.

here is some solution or alternative plan.

https://stackoverflow.com/questions/4610086/pthread-cancel-alternatives-in-android-ndk

**Comment by polymonster** [comment]
Many other platforms also do not allow to destroy in this way.

none of the code I am using,  actually uses thread_destory.. all threads close themselves and they use semaphores to signal shutdown, so I might just remove thread_destory all together...
