### ISSUE TITLE
error when loading shared libraries libfmod.so.11 : no such file or dir

### ISSUE THREAD

**Issue by Madour** [polymonster/pmtech#50]
Hello, I wanted to try out the engine, I followed build instructions, everything went fine.

But when I run any example in examples/bin/linux folder, i get `error while loading shared libraries: libfmod.so.11: cannot open shared object file: No such file or directory`.

Looking into the directory, it seems there is a libfmod.so and a libfmodL.so but no libfmod.so.11 unfortunately.

Do you know how to fix this ? (tried renaming libfmod.so to libfmod.so.11 but didn't work)

**Comment by polymonster** [comment]
Hey,

I am aware of this problem, it only should affect the play_sound and audio_player samples. I am not sure what the issue is or how to fix it yet, but I am also seeing the same thing.

**Comment by Madour** [comment]
thanks for your answer, but it seems all examples are affected on my side (tried ik, sdf_shadow, vertex_stream_out ant others ...), very unfortunate . I guess i'll try building it on windows instead for now

**Comment by polymonster** [comment]
Windows and Mac get more use and testing but I do have a Linux machine too and have been working on it recently, I’ll take a look at fixing the Linux build tomorrow

**Comment by polymonster** [comment]
Hey, I took a quick look at this and have fixed it, The rpath wasn't being set to look in the exe dir.

Let me know if it works for you :)

**Comment by Madour** [comment]
Hey ! I didn't have much time to test yesterday sorry.
Retried building everything and running it, everything works perfectly ! Awesome !
I'll try to dive into your engine, especially to learn how you implemented multiple backends, is there a place to ask questions like a discord or something ?
Thx

**Comment by polymonster** [comment]
Good stuff, glad to hear its working... I don't have anywhere to ask but can setup a discord server, I'll add the link on the readme in the repo.

If you are interested in the multiple rendering backend support... I am working on another engine at work which has some slightly better approaches in that you can dynamically change the rendering backend at run time, its a feature I want to eventually get in pmtech but if you have questions I can certainly answer them when I get time.

**Comment by polymonster** [comment]
discord: https://discord.gg/3yjXwJ8wJC
